# Site settings
email: studio@xxix.co
description: > # this means to ignore newlines until "baseurl:"
  Documentation for the Wordpress site created for AIGA Eye on Design found at eyeondesign.aiga.org. The site was designed by Leta Sobierajski.
baseurl: "/aiga-eod-docs" # the subpath of your site, e.g. /blog/
client: "AIGA Eye on Design"

# Build settings
markdown: kramdown
